### ISSUE TITLE
Sublime Text 3 Support (Python 3.3)

### ISSUE THREAD

**Issue by HarryPehkonen** [AxxL/sublime-toggle-readonly#2]
view.set_read_only() takes boolean.  Please change 0 and 1 to False and True :D

**Comment by AxxL** [comment]
Tried it with an if > 3000. Elegant?

**Comment by HarryPehkonen** [comment]
Sigh!  :)

**Comment by FrelEsquif** [comment]
`NameError: global name 'true' is not defined`

Boolean are case sensitive, right?

**Comment by AxxL** [comment]
Thank you. I've merged xu-cheng pull-request.

**Comment by deMax3** [comment]
I open a file from the command line or file manager. How to set read-only mode automatically?

**Comment by AxxL** [comment]
@deMax3 Sorry, I don't know. The command in the Python file goes to the view (self).
